name: Update plugins
on:
  workflow_dispatch:
env:
  GIT_AUTHOR_NAME: ${{ github.actor }}
  GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com

jobs:
  # ugly way to share the plugin list
  plugin_list:
    runs-on: ubuntu-latest
    outputs:
      plugins: ${{ steps.set-list.outputs.plugins }}
    steps:
    - name: Write the plugin list
      run: echo '["foreman_ansible"]' > plugin_list.json
    - name: Set the plugins list
      id: set-list
      run: |
        PLUGINS=$(cat plugin_list.json)
        echo "::set-output name=plugins::$PLUGINS"

  # Bump the plugins on RPM
  bump_plugin_rpm:
    needs: plugin_list
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gem:
          - ${{ fromJson(needs.plugin_list.outputs.plugins) }}
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install -y rpm curl jq git-annex python3-pip
        sudo pip3 install semver
        sudo gem install gem2rpm
        sudo apt-get install -y libcurl4-openssl-dev
        sudo curl --create-dirs -o /usr/local/bin/spectool https://pagure.io/rpmdevtools/raw/26a8abc746fba9c0b32eb899b96c92841a37855a/f/spectool.in
        sudo chmod +x /usr/local/bin/spectool
    - name: Fetch latest plugin gem info
      id: latest_gem
      run: echo "::set-output name=version::$(curl -s https://rubygems.org/api/v1/gems/${{ matrix.gem }}.json | jq -r .version)"
    - name: Checkout RPM
      uses: actions/checkout@v2
      with:
        ref: rpm/develop
    - name: Initialize git annex
      run: git annex init
    - name: Try to bump plugin
      run: |
        alias rpmdev-packager="echo $GIT_AUTHOR_NAME <$GIT_AUTHOR_EMAIL>"
        ./bump_rpm.sh packages/plugins/rubygem-${{ matrix.gem }} ${{ steps.latest_gem.outputs.version }}
      env:
        SKIP_GIT_COMMIT: 1
    - name: Open a PR
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "Update ${{ matrix.gem }} to ${{ steps.latest_gem.outputs.version }}"
        branch: "bump_rpm/${{ matrix.gem }}"
        title: "Update ${{ matrix.gem }} to ${{ steps.latest_gem.outputs.version }}"
        body: ''
        delete-branch: true

  # Bump the plugins on DEB
  bump_plugin_deb:
    needs: plugin_list
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gem:
          - ${{ fromJson(needs.plugin_list.outputs.plugins) }}
    steps:
    - name: Set plugin package name
      id: package_info
      run: echo "::set-output name=name::ruby-$(echo ${{ matrix.gem }} | tr _ -)"
    - name: Checkout DEB
      uses: actions/checkout@v2
      with:
        ref: deb/develop
    - name: Fetch latest plugin gem info
      id: latest_gem
      run: echo "::set-output name=version::$(curl -s https://rubygems.org/api/v1/gems/${{ matrix.gem }}.json | jq -r .version)"
    - name: Update package
      run: ./scripts/update_package.rb --name ${{ steps.package_info.outputs.name }} --version ${{ steps.latest_gem.outputs.version }}
    - name: Open a PR
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "Update ${{ matrix.gem }} to ${{ steps.latest_gem.outputs.version }}"
        branch: "bump_deb/develop-${{ matrix.gem }}"
        title: "Update ${{ matrix.gem }} to ${{ steps.latest_gem.outputs.version }}"
        body: ''
        delete-branch: true
