name: Update plugins on DEB
on:
  workflow_dispatch:

jobs:
  bump_plugin_deb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        plugin:
          - foreman_ansible
    steps:
    - name: Set plugin package name
      id: package_info
      run: echo "::set-output name=name::$(echo $GEM_NAME | tr _ -)"
      env:
        GEM_NAME: ${{ matrix.plugin }}
    - name: Checkout DEB
      uses: actions/checkout@v2
      with:
        ref: deb/develop
    - name: Fetch latest plugin gem info
      id: latest_gem
      run: |
        curl_output=$(curl -s https://rubygems.org/api/v1/gems/${GEM_NAME}.json)
        echo "::set-output name=version::$(jq -r .version <<<$curl_output)"
        echo "::set-output name=uri::$(jq -r .gem_uri <<<$curl_output)"
      env:
        GEM_NAME: ${{ matrix.plugin }}
    - name: Update package
      run: |
        git config user.name $AUTHOR_NAME
        git config user.email $AUTHOR_MAIL
        ./scripts/update_package.rb --name ruby-$PACKAGE_NAME --version $NEW_VERSION
      env:
        NEW_VERSION: ${{ steps.latest_gem.outputs.version }}
        PACKAGE_NAME: ${{ steps.package_info.outputs.name }}
        AUTHOR_NAME: ${{ github.actor }}
        AUTHOR_MAIL: ${{ github.actor }}@users.noreply.github.com
    - name: Open a PR
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "Updates ${{ matrix.plugin }} to ${{ steps.latest_gem.outputs.version }}"
        branch: "bump_deb/develop-${{ matrix.plugin }}"
        title: "Updates ${{ matrix.plugin }} to ${{ steps.latest_gem.outputs.version }}"
        body: ''
